MRuby::Gem::Specification.new('mruby-slipstreamio') do |spec|
  spec.license = 'Apache-2.0'
  spec.author  = 'Hendrik Beskow'
  spec.summary = 'The io_uring submission/completion API, run on select(2)'

  # THE DECISION LIVES HERE, and only here. The header itself never
  # looks for the implementation it stands in for, and neither does any
  # consumer: they write `#include <liburing.h>` and call the
  # functions. This block is the packaging layer that decides what that
  # resolves to - the job libkqueue leaves to the distribution.
  #
  # mruby-io-uring is the dependency because it is the one that knows:
  # it runs liburing's own ./configure && make on this host and copies
  # the installed headers into its include/ when that works, or
  # degrades (URING_AVAILABLE = false) when it does not. Every mrbgem's
  # include/ is on every other mrbgem's search path, so "did it work"
  # is answerable by looking.
  spec.add_dependency 'mruby-io-uring'

  installed = "#{spec.dir}/include/liburing.h"

  # Removed BEFORE looking, every build. Otherwise the search below
  # would find last build's own copy and conclude a real liburing is
  # present - and a host that gained liburing since would keep being
  # served the select implementation forever. The question has to be
  # asked against everyone else's include/, not ours.
  FileUtils.rm_f installed

  if spec.cc.search_header 'liburing.h'
    # A real liburing is on the path (mruby-io-uring built it). Nothing
    # to install and nothing to say: this gem contributes its
    # implementation under its own name only, and no consumer reaches
    # it. Silence is the correct output of a decision that changed
    # nothing.
  else
    # No liburing anywhere. Take over the name, so that source written
    # against that API compiles and runs here unchanged. A forwarding
    # header rather than a copy of the implementation: one file is the
    # source of truth, and a stale duplicate cannot drift from it.
    #
    # Build output, regenerated every build - not tracked source, see
    # .gitignore.
    FileUtils.mkdir_p "#{spec.dir}/include"
    File.write(installed, <<~HDR)
      // GENERATED by mruby-slipstreamio's mrbgem.rake - do not edit, do
      // not commit. This host has no liburing, so the API name is
      // pointed at the implementation that does exist here.
      #pragma once
      #include <slipstreamio.h>
    HDR
    warn 'mruby-slipstreamio: no liburing on this host -- <liburing.h> now resolves to ' \
         'slipstreamIO (the select(2) implementation: correct, NOT fast).'
  end
end
